services:
    kafkabotdb:
        container_name: KafkaBOT_DB
        image: postgres:latest
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            PGDATA: /data/postgres
            PGPORT: '${POSTGRES_DEFAULT_PORT}'
        volumes:
            - kafkabotdb:/data/postgres
        ports:
            - '${POSTGRES_MAP_PORT}:${POSTGRES_DEFAULT_PORT}'
        networks:
            - kafkabot_network
        healthcheck:
            test: ['CMD-SHELL', "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
            interval: 30s
            timeout: 60s
            retries: 5
            start_period: 80s
        restart: always

    kafkabotapp:
        container_name: KafkaBOT_APP
        build: .
        env_file:
            - .env
        ports:
            - '8000:8000'
        depends_on:
            kafkabotdb:
                condition: service_healthy
        networks:
            - kafkabot_network
        restart: always

networks:
    kafkabot_network:
        name: kafkabot_network
        driver: bridge

volumes:
    kafkabotdb:
